export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  OTPVERIFY: "/otpverify",
  FORGOTPASSWORD: "/forgotpassword",
  SIGNUP: "/signup",
  REGISTERSUCCESS: "/registersuccess",
  REGISTERFAILURE: "/registerfailure",
  CHECKINBOX: "/checkinbox",
  DASHBOARDCREATE: "/dashboard/create",
  DASHBOARD: "/dashboard",
  DASHBOARDWITHDRAWAL: "/dashboard/withdrawal",
  DASHBOARDEXAMCONTENT: "/dashboard/content",
  DASHBOARDINDIVIDUALEXAMCONTENT: "/dashboard/individualexam",
  DASHBOARDADMIN: "/dashboard/admin",
  DASHBOARDADMINSTUDENT: "/dashboard/admin/student",
  DASHBOARDADMINEXAM: "/dashboard/admin/exam",
  DASHBOARDCATEGORIES: "/dashboard/categories",
  DASHBOARDCATEGORIESDETAILS: "/dashboard/categories/:id",
  DASHBOARDADMINEXAMINERS: "/dashboard/admin/examiners",
  DASHBOARDADMINVIEWWALLET: "/dashboard/admin/viewwallet",
  DASHBOARDADMINWITHDRAWAL: "/dashboard/admin/withdrawal",
  DASHBOARDADMINVIEWREQUEST: "/dashboard/admin/viewrequest",
  DASHBOARDADMINVIEWTRANSACTION: "/dashboard/admin/viewtransaction",
};
